### ISSUE TITLE
Compiling Electrum for windows !!

### ISSUE THREAD

**Issue by mmitech** [mazaclub/electrum-dash#3]
I am having troubles compiling Electrum for windows, I tried to build it with wine on Ubuntu with the script provided, it build an exe that does nothing when clicked on !

Can you please give me instructions on how to build this  correctly for windows ?

**Comment by guruvan** [comment]
Apologies - These are old scripts imported from upstream Electrum which do not appear to be terribly up to date - we do not use these and they should be removed. 

The Release pages have correct information on our most recent builds. https://github.com/mazaclub/electrum-dash/releases/tag/v2.4.1rc2

The Current 2.4.1rc2 build is available here: https://github.com/guruvan/mazaclub-release/tree/dash
The build is rather complicated, and will require you to have docker installed. 
To build just Windows binary from your local repo
```
git clone https://github.com/mazaclub/electrum-dash
cd electrum-dash
git checkout release/2.4.1rc2
cd contrib
git submodule init
git submodule update 
cd mazaclub-release
./buildWindows 2.4.1rc2 local
```

**Comment by guruvan** [comment]
The build will be integrated at a later time after the repo is moved to official resting place.

**Comment by mmitech** [comment]
Cool, I will try that and let you know. Thank you.

**Comment by mmitech** [comment]
I think it should be git checkout dash

**Comment by guruvan** [comment]
In electrum-dash you should checkout the current release branch (rather than master!) 

The submodule init/update should give you the correct commit from https://github.com/guruvan/mazaclub-release (branch dash)

**Comment by mmitech** [comment]
OK understood, thank you, will keep you updated.

**Comment by mmitech** [comment]
Works as a charm. Thank you.

**Comment by RdeWilde** [comment]
The original build as in first post, does not start because it is missing modules like x11_hash. How would one go to add these?
